In [25]:
import numpy as np
import pandas as pd

In [26]:
np.random.seed(23)

mu_vector1 = np.array([0,0,0])
cov_vector1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vector1,cov_vector1,20)
df = pd.DataFrame(class1_sample, columns=['f1', 'f2', 'f3'])
df['target'] = 1


mu_vector2 = np.array([0,0,0])
cov_vector2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vector2,cov_vector2,20)
df1 = pd.DataFrame(class2_sample, columns=['f1', 'f2', 'f3'])
df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)
df = df.sample(40)
df

f1        f2        f3  target
2  -0.367548 -1.137460 -1.322148       1
34 -0.822939 -1.598109  0.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
29  0.425140  0.441152 -0.817439       0
31  1.224431 -0.769599  0.192120       0
4   0.322272  0.060343 -1.043450       1
32 -1.723253  0.461259 -1.085367       0
33  1.823378 -1.332863  1.637391       0
36 -2.389866 -0.333274  0.343517       0
18 -0.331617 -1.632386  0.619114       1
0   0.666988  0.025813 -0.777619       1
5  -1.009942  0.441736  1.128877       1
39 -0.615135  0.323546 -1.103193       0
22  0.676860  3.187503 -1.080565       0
8   0.241106 -0.952510 -0.136267       1
15 -0.045438  1.040886 -0.094035       1
19 -0.992574 -0.161346  1.192404       1
30  0.437892  0.099723  0.065406       0
25 -0.709254 -0.133025 -0.017357       0
21 -0.268142 -0.482559  1.244610       0
37 -2.027861  0.131416  1.603234       0
16 -0.420844 -0.551989 -0.121098       1
38 -1.764314  0.566504  0.548788       0
27  1.011059  0.920996  1.933090       0
26 -0.101093 -0.564040 -0.179036       0
23  0.010229  0.437830  1.327788       0
1   0.948634  0.701672 -1.051082       1
10  1.415320  0.457711  0.728876       1
20  0.250737 -0.813616  0.703624       0
28 -0.795363 -1.011535  2.150780       0
24 -0.251145  1.593111  0.170818       0
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
17  0.190141  0.512137  0.131538       1
13 -0.022539  0.013422  0.935945       1
9   1.267248  0.173634 -1.223255       1
35  0.233898 -0.947222 -1.261576       0
3   1.772258 -0.347459  0.670140       1

In [27]:
import plotly.express as px

fig = px.scatter_3d(df, x=df['f1'], y=df['f2'], z=df['f3'], color=df['target'].astype('str'))
fig.show()

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df.iloc[: ,0:3] = scaler.fit_transform(df.iloc[:, 0:3])

In [29]:
cov_matrix = np.cov([df.iloc[:, 0], df.iloc[:, 1], df.iloc[:, 2]])
cov_matrix

array([[ 1.02564103,  0.06781177, -0.12497686],
       [ 0.06781177,  1.02564103, -0.15241116],
       [-0.12497686, -0.15241116,  1.02564103]])

In [30]:
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

In [31]:
eigen_values

array([1.25911792, 0.95953081, 0.85827434])

In [32]:
%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['f1'], df['f2'], df['f3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['f1'].mean()], [df['f2'].mean()], [df['f3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df['f1'].mean(), v[0]], [df['f2'].mean(), v[1]], [df['f3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

plt.show()

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

<Figure size 700x700 with 1 Axes>

In [35]:
pc = eigen_vectors[0:2]
pc

array([[-0.51038783, -0.78846385,  0.34326234],
       [-0.569092  ,  0.60894401,  0.55255904]])

In [39]:
transformed_df = np.dot(df.iloc[:, 0:3], pc.T)
new_df = pd.DataFrame(transformed_df, columns=['pc1', 'pc2'])
new_df['target'] = df['target'].values
new_df

pc1       pc2  target
0   0.560815 -1.471948       1
1   1.740278 -0.643400       0
2  -0.706342 -0.080489       1
3  -0.786474 -1.876564       1
4   1.105696  1.622028       1
5  -1.007205 -0.501748       0
6   0.066075 -1.137493       0
7  -0.707244 -0.841943       1
8  -0.145920  0.443610       0
9   0.818777 -0.974273       0
10  1.380234  1.081378       0
11  1.690608 -0.684825       1
12 -0.736369 -0.883809       1
13  0.356412  1.371690       1
14 -0.534906 -0.222539       0
15 -3.639677  1.086177       0
16  0.554478 -0.956725       1
17 -1.057612  0.571023       1
18  0.903554  0.989539       1
19 -0.389170 -0.221199       0
20  0.307473  0.153240       0
21  0.876465  0.434178       0
22  1.266369  1.955632       0
23  0.507850 -0.339384       1
24  0.377363  1.497789       0
25 -0.691241  1.146619       0
26  0.351891 -0.543816       0
27 -0.031340  0.968812       0
28 -1.560410 -0.727252       1
29 -0.906778 -0.082547       1
30  0.734668 -0.372749       0
31  1.913960  0.874515       0
32 -1.354210  1.207282       0
33 -0.779058  0.208813       1
34  1.463877  0.068281       1
35 -0.616008  0.224216       1
36  0.214565  0.465789       1
37 -1.302602 -1.349747       1
38  0.141700 -1.611702       0
39 -0.380544 -0.846459       1

In [41]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['pc1'],
                 y=new_df['pc2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()