In [1]:
from sklearn.datasets import make_regression

import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [2]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [3]:
X

array([[ 0.41421248,  2.00189025],
       [-0.88187437, -0.05407071],
       [-0.26714456, -1.41539411],
       [-2.23139564, -0.66518609],
       [-1.17449265, -1.49140463],
       [-0.8595063 ,  1.74248463],
       [ 0.41809342, -0.80479458],
       [ 1.10078493,  0.94926271],
       [ 1.05978893, -2.54314637],
       [-0.64269722, -1.36109521],
       [ 0.18943132,  2.16248838],
       [-1.15205744,  0.00875931],
       [-0.83081902,  1.1747222 ],
       [ 0.88687477,  0.5357053 ],
       [ 0.07479481,  0.18299184],
       [ 0.07543459,  0.77986566],
       [-0.34501734,  0.78762184],
       [ 0.80243559,  0.3460159 ],
       [ 1.89584184,  0.23287841],
       [-1.57900608,  0.39709672],
       [ 0.50260742, -0.74792138],
       [ 0.28451603,  1.20886183],
       [-0.01695396,  0.08417771],
       [-0.71946576,  0.45540345],
       [-0.74899828,  0.05994346],
       [-1.26189867, -1.2684811 ],
       [ 0.02433136,  0.83241854],
       [-0.16408793,  0.44598777],
       [ 0.51405253,

In [4]:
y

array([ 148.11690693,  -11.02103113, -203.28679683, -154.99982134,
        -57.21694922,   97.69938727,   42.57356147,   49.71452401,
        -92.30975704, -176.16358427,  220.26844569,  -63.50686412,
         74.40548456,   36.77624112,   21.12654703,  107.3916309 ,
         78.03020804,   85.85729167,   17.34597116,  -30.46363366,
        -30.55110506,  162.02816509,  -13.18289093,   26.5273439 ,
         32.80720645,  -88.94463368,   18.75123062,   86.89462125,
        -19.95249097,  -49.22396206,   77.63711876,   24.05715284,
        -95.71189466,   95.53891615,   19.46222055,   77.71358377,
         86.73659161, -160.92199952,   56.47792513,    9.40891097,
        -78.87618076,  144.93562273,  119.65729087,   23.98343784,
       -149.50475592,   59.18736837, -125.84129577,  -51.71581668,
        103.57820763,   13.3466073 ,  -71.87439002, -171.43754088,
        -37.7191228 ,   -3.36385033,  -51.03874476,   96.67615045,
          2.22312681,   32.08236317,  -44.70909121, -159.80443

In [5]:
df = pd.DataFrame({'feature1':X[:, 0], 'feature2':X[:, 1], 'target':y})
df

feature1  feature2      target
0   0.414212  2.001890  148.116907
1  -0.881874 -0.054071  -11.021031
2  -0.267145 -1.415394 -203.286797
3  -2.231396 -0.665186 -154.999821
4  -1.174493 -1.491405  -57.216949
..       ...       ...         ...
95 -0.997484  0.101840   28.215209
96  0.370006  0.232960   13.336975
97 -0.072952 -0.209828  -17.131305
98 -0.814780 -0.589494  -69.727432
99  1.248888 -0.738426   -5.702193

[100 rows x 3 columns]

In [6]:
fig = px.scatter_3d(data_frame=df, x='feature1', y='feature2', z='target')

fig.show()

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [8]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [9]:
y_pred = lr.predict(X_test)

In [10]:
print("MAE = ", mean_absolute_error(y_test, y_pred))
print("MSE = ", mean_squared_error(y_test, y_pred))
print("R2Score = ", r2_score(y_test, y_pred))

MAE =  36.88554193850253
MSE =  2305.55595241323
R2Score =  0.6761228659442566


In [21]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

z_final = lr.predict(final).reshape(10,10)

z = z_final

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

In [22]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [23]:
lr.coef_

array([40.88557526, 68.22412962])

In [25]:
lr.intercept_

3.4164835985105118